#ifndef SMARTPOINTERSV2_OPERATIONS_H
#define SMARTPOINTERSV2_OPERATIONS_H

enum Operations {
    PLUS,
    MINUS,
    DIV,
    MULT,
    SIN,
    COS,
    NIL
};

#endif // SMARTPOINTERSV2_OPERATIONS_H